services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: vector_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollamas
    entrypoint: >
      sh -c "ollama serve & sleep 5 && ollama pull nomic-embed-text && wait"

volumes:
  ollama_data: